export default [
  { id: 'list', method: 'GET', url: '/users' },
  { id: 'retrieve', method: 'GET', url: '/users/:id' },
  { id: 'getAuthenticated', method: 'GET', url: '/users/me' },
  { id: 'follow', method: 'POST', url: '/users/:id/follow' },
  { id: 'unfollow', method: 'POST', url: '/users/:id/unfollow' },
  { id: 'block', method: 'POST', url: '/users/:id/block' },
  { id: 'unblock', method: 'POST', url: '/users/:id/unblock' },
  { id: 'listBlocked', method: 'GET', url: '/users/:id/blocked' },
  { id: 'listTopics', method: 'GET', url: '/users/:id/topics' },
  { id: 'listReplies', method: 'GET', url: '/users/:id/replies' },
  { id: 'listFavorites', method: 'GET', url: '/users/:id/favorites' },
  { id: 'listFollowers', method: 'GET', url: '/users/:id/followers' },
  { id: 'listFollowing', method: 'GET', url: '/users/:id/following' },
] as const
